controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


add_habitant:
    path: /add/habitant
    methods: [POST]
    controller: App\Controller\AddHabitantController::addHabitant