controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


accueil_redirection:
    path: /redirection
    controller: App\Controller\AccueilController::redirection

authentification:
    path: /authentification
    methods: [POST]
    controller: App\Controller\AuthentificationController::authentification

add_habitant:
    path: /add/habitant
    methods: [POST]
    controller: App\Controller\AddHabitantController::addHabitant


show_habitant:
    path: /show/habitant
    controller: App\Controller\ShowHabitantController::getHabitantData
    methods: ['GET']

app_delete_habitant:
    path: /delete/habitant/{id}
    controller: App\Controller\DeleteHabitantController::deleteHabitant
    methods: ['DELETE']


app_get_habitant:
    path: /get/habitant/{id}
    controller: App\Controller\GetHabitantController::getHabitantById
    methods: ['GET']    

app_update_habitant:
    path: /update/habitant/{id}
    controller: App\Controller\UpdateHabitantController::updateHabitantById
    methods: ['PUT']